name: Build and publish glint frontend and backend

on: [push]

jobs:
  oci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/vectorsquad/glint:latest

      - name: Ensure Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            repo_exists() {
              test -d ${{ github.repository }}
            }
            
            cd_repo() {
              cd ${{ github.event.repository.name }}
            }

            update_repo() {
              repo_exists &&
              echo "Updating repo..." &&
              cd_repo &&
              git pull
            }
            
            clone_repo() {
              ! repo_exists &&
              echo "Cloning repo..." &&
              git clone "https://github.com/${{ github.repository }}.git" &&
              cd_repo
            }
            
            update_repo || clone_repo

            echo "Tearing down containers..."
            podman kube down ./kube.yml
            
            echo "Playing containers..."
            podman kube play ./kube.yml 
