name: Build and publish glint frontend and backend

on: [push]

jobs:
  oci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/vectorsquad/glint:latest

      - name: Ensure Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            test -d ${{ github.repository }} || git clone "https://github.com/${{ github.repository }}.git"
            cd ${{ github.event.repository.name }}
            git pull
            sh ./ensure.sh

            echo "Tearing down containers..."
            podman kube down ./kube.yml
            
            echo "Playing containers..."
            podman kube play ./kube.yml 
