name: Build, Publish and Ensure

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish OCI Image
        run: earthly --ci --push +image-push
      
  # ensure-production:
  #   runs-on: ubuntu-latest
  #   needs: [publish-image]
  #   steps:
  #     - name: Ensure Production Server
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.PROD_HOST }}
  #         username: ${{ secrets.PROD_USERNAME }}
  #         key: ${{ secrets.PROD_SSH_KEY }}
  #         script_path: scripts/ensure.sh
